FROM node:18-alpine
WORKDIR /app
# Copiar archivos de dependencias
COPY package*.json ./
#probar cambios
# Instalar dependencias


RUN npm install --ignore-scripts
RUN npx --ignore-scripts some-package
RUN npm exec --ignore-scripts -- some-package
# Copiar código de la aplicación
COPY src/ ./src/
COPY sql/ ./sql/
COPY uploads/ ./uploads/
# Crear directorio para uploads si no existe
RUN mkdir -p uploads/contracts
# Exponer puerto
EXPOSE 3000
# Comando para iniciar la aplicación
CMD ["node", "src/app.js"]